version: '3.9'

services:
  backend:
    build: .
    hostname: ${KARMA_APP_POSTS_HOST}
    ports:
      - 50051:50051
    networks:
      - net
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    hostname: ${KARMA_APP_POSTS_DB_HOST}
    ports:
      - 27017:27017
    networks:
      - net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${KARMA_APP_POSTS_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${KARMA_APP_POSTS_DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${KARMA_APP_POSTS_DB_NAME}
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb
      - ./keyfile:/opt/keyfile/
    healthcheck: # 94 is an error code returned when rs is not initiated.
      test: test "$$(mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet --eval "try {rs.status().ok} catch(e) {if (e.code == 94) {rs.initiate().ok} else {0} }")" -eq 1
      interval: 10s
      start_period: 30s
    command: mongod --replSet rs0 --keyFile /opt/keyfile

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${KARMA_APP_POSTS_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${KARMA_APP_POSTS_DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${KARMA_APP_POSTS_DB_NAME}
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  db-data:
    driver: local
  db-config:
    driver: local

networks:
  net:
    driver: bridge
